services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: object_store
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USERNAME: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/object_store
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: admin
      MINIO_URL: http://minio:9000
      MINIO_USERNAME: minio
      MINIO_PASSWORD: minio123
    ports:
      - "8080:8080"

volumes:
  pgdata:
  minio_data: